# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [41]:
weather_df = pd.read_csv("./output_data/city_weather_data.csv")
# Dropped extra index column
weather_df.drop(axis=1,labels='Unnamed: 0',inplace=True)
weather_df.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,Totma,100,RU,1581512691,97,59.97,42.76,32.74,9.84
1,Cabo San Lucas,4,MX,1581512680,85,22.89,-109.91,51.01,5.32
2,Wonthaggi,0,AU,1581512691,91,-38.60,145.59,68.00,8.01
3,Norman Wells,40,CA,1581512691,82,65.28,-126.83,-16.60,6.93
4,Puerto Ayora,20,EC,1581512692,78,-0.74,-90.35,78.80,9.17

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [119]:
# Cofigure map with api key and set locations from data frame columns
gmaps.configure(api_key=g_key)
heat_locations = weather_df[["Lat", "Lng"]]

In [124]:
# Some formating to try get the map to center
figure_layout = {'600px': '500px', '1': '0 auto 0 auto'}
fig = gmaps.figure(center=(0,0), zoom_level=1.6, layout=figure_layout)
# Add heat layer using humidity as weights and 100% as max humidity
heat_layer = gmaps.heatmap_layer(heat_locations, weights=weather_df['Humidity'], 
                                 max_intensity=100,
                                 dissipating = False,
                                 point_radius = 2.5)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [95]:
# Setting idea conditions between 60-80 F and low winds low humidity
hotel_df = weather_df.loc[(weather_df["Max Temp"]>60)&(weather_df["Max Temp"]<80)&
                          (weather_df["Wind Speed"]<15)&(weather_df["Humidity"]<30)]
hotel_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
67,Nalut,78,LY,1581512705,11,30.33,10.85,69.51,2.51
157,Sakakah,0,SA,1581512476,20,29.97,40.21,62.60,5.82
201,Bilma,95,NE,1581512732,13,18.69,12.92,72.46,6.55
214,Jalu,0,LY,1581512735,15,29.03,21.55,73.29,11.99
335,Waddan,0,LY,1581512762,11,29.16,16.14,71.96,7.54
365,Sabha,7,LY,1581512768,13,27.04,14.43,72.05,7.05
415,Ringas,35,IN,1581512780,23,27.35,75.57,77.00,3.36
502,Pimentel,81,PE,1581512799,29,-6.84,-79.93,66.20,9.17

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [96]:
# Add empty column named hotel name
hotel_df["Hotel Name"]=''
hotel_df

C:\Users\Chris\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
67,Nalut,78,LY,1581512705,11,30.33,10.85,69.51,2.51,
157,Sakakah,0,SA,1581512476,20,29.97,40.21,62.60,5.82,
201,Bilma,95,NE,1581512732,13,18.69,12.92,72.46,6.55,
214,Jalu,0,LY,1581512735,15,29.03,21.55,73.29,11.99,
335,Waddan,0,LY,1581512762,11,29.16,16.14,71.96,7.54,
365,Sabha,7,LY,1581512768,13,27.04,14.43,72.05,7.05,
415,Ringas,35,IN,1581512780,23,27.35,75.57,77.00,3.36,
502,Pimentel,81,PE,1581512799,29,-6.84,-79.93,66.20,9.17,

In [106]:
# Iterate through each row of hotel_df, for each row search for the closing lodging lcation and store into hotel name
for index, row in hotel_df.iterrows():
    # Setting query parameters
    target_coordinates = f"{row['Lat']}, {row['Lng']}"
    target_radius = 5000
    target_type = "lodging"
    params = {
        "location": target_coordinates,
        "radius": target_radius,
        "type" :target_type,
        "key": g_key
    }  
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    response = requests.get(base_url, params=params).json()
    try:
        # If json traversal succeeds then store info
        hotel_df.at[index,"Hotel Name"]=response['results'][0]['name']
    except:
        # If json traversal fails then no hotels were found and drop current row
        print("no lodging were found")
        hotel_df.drop(index,inplace=True)

no lodging were found

C:\Users\Chris\Anaconda3\lib\site-packages\pandas\core\frame.py:4102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [109]:
# Setting varible reference to use the code from next cell
narrowed_city_df = hotel_df

In [125]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [126]:
# Add marker layer ontop of heat map
# Setting a new figure
fig2 = gmaps.figure(center=(0,0), zoom_level=1.6, layout=figure_layout)
# Create a symbol layer, using parts of code from class activity and the two variable from the cell above
hotel_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    scale=5,
    info_box_content=hotel_info
)
# Add layers to fig2
fig2.add_layer(hotel_layer)
# Add heat layer created earlier
fig2.add_layer(heat_layer)
# Display Map
fig2

Figure(layout=FigureLayout(height='420px'))